name: Despliegue Hogwarts API a Elastic Beanstalk

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read
  packages: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Verificar
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Construir bootJar (skip tests)
        run: ./gradlew clean bootJar -x test

      - name: Inicie sesiÃ³n en el Registro de contenedores de GitHub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Nombre de Imagen en Minusculas
        run: |
          echo "IMAGE_NAME=$(echo ghcr.io/${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Crear y enviar una imagen de Docker
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE_NAME }}:${{ github.run_number }}
          no-cache: true
          pull: true

      - name: Generado docker-compose.yml
        run: |
          cat > docker-compose.yml << 'EOF'
          services:
            app:
              image: ${{ env.IMAGE_NAME }}:${{ github.run_number }}
              ports:
                - "80:8080"
              environment:
                - SPRING_DATASOURCE_URL
                - SPRING_DATASOURCE_USERNAME
                - SPRING_DATASOURCE_PASSWORD
              restart: always
          EOF

      - name: Despliegue a Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_session_token: ${{ secrets.AWS_SESSION_TOKEN }}
          region: us-east-1
          application_name: Docker_Hogwarts
          environment_name: DockerHogwarts-env
          version_label: "hogwarts-v-${{ github.run_number }}"
          deployment_package: docker-compose.yml